spring:
  cassandra:
    username: admin
    password: password
    contact-points: localhost
    port: 9042
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1
    request:
      timeout: 5000

logging:
  level:
    org.springframework.data.cassandra: DEBUG
