server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: DemoDisk
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:ERROR}
    ru.yandex.enrollment: ${LOGGING_LEVEL:ERROR}
    org.hibernate.type: ${LOGGING_HIBERNATE_LEVEL:ERROR}
